/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthorSlugRouteImport } from './routes/author.$slug'
import { Route as BriefIndexRouteImport } from './routes/brief.index'
import { Route as BriefEditionRouteImport } from './routes/brief.$edition'
import { Route as ChartsIndexRouteImport } from './routes/charts.index'
import { Route as ChartsSlugRouteImport } from './routes/charts.$slug'
import { Route as ChartsTicketPriceIndexRouteImport } from './routes/charts.ticket-price-index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsSlugRouteImport } from './routes/reports.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorSlugRoute = AuthorSlugRouteImport.update({
  id: '/author/$slug',
  path: '/author/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefIndexRoute = BriefIndexRouteImport.update({
  id: '/brief/',
  path: '/brief/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefEditionRoute = BriefEditionRouteImport.update({
  id: '/brief/$edition',
  path: '/brief/$edition',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsIndexRoute = ChartsIndexRouteImport.update({
  id: '/charts/',
  path: '/charts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsSlugRoute = ChartsSlugRouteImport.update({
  id: '/charts/$slug',
  path: '/charts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsTicketPriceIndexRoute = ChartsTicketPriceIndexRouteImport.update({
  id: '/charts/ticket-price-index',
  path: '/charts/ticket-price-index',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSlugRoute = ReportsSlugRouteImport.update({
  id: '/reports/$slug',
  path: '/reports/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/methodology': typeof MethodologyRoute
  '/newsletter': typeof NewsletterRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/author/$slug': typeof AuthorSlugRoute
  '/brief/$edition': typeof BriefEditionRoute
  '/charts/$slug': typeof ChartsSlugRoute
  '/charts/ticket-price-index': typeof ChartsTicketPriceIndexRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/brief/': typeof BriefIndexRoute
  '/charts/': typeof ChartsIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/methodology': typeof MethodologyRoute
  '/newsletter': typeof NewsletterRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/author/$slug': typeof AuthorSlugRoute
  '/brief/$edition': typeof BriefEditionRoute
  '/charts/$slug': typeof ChartsSlugRoute
  '/charts/ticket-price-index': typeof ChartsTicketPriceIndexRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/brief': typeof BriefIndexRoute
  '/charts': typeof ChartsIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/authors': typeof AuthorsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/methodology': typeof MethodologyRoute
  '/newsletter': typeof NewsletterRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/author/$slug': typeof AuthorSlugRoute
  '/brief/$edition': typeof BriefEditionRoute
  '/charts/$slug': typeof ChartsSlugRoute
  '/charts/ticket-price-index': typeof ChartsTicketPriceIndexRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/brief/': typeof BriefIndexRoute
  '/charts/': typeof ChartsIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/authors'
    | '/contact'
    | '/cookies'
    | '/methodology'
    | '/newsletter'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/author/$slug'
    | '/brief/$edition'
    | '/charts/$slug'
    | '/charts/ticket-price-index'
    | '/insights/$slug'
    | '/reports/$slug'
    | '/brief/'
    | '/charts/'
    | '/insights/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/authors'
    | '/contact'
    | '/cookies'
    | '/methodology'
    | '/newsletter'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/author/$slug'
    | '/brief/$edition'
    | '/charts/$slug'
    | '/charts/ticket-price-index'
    | '/insights/$slug'
    | '/reports/$slug'
    | '/brief'
    | '/charts'
    | '/insights'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/authors'
    | '/contact'
    | '/cookies'
    | '/methodology'
    | '/newsletter'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/author/$slug'
    | '/brief/$edition'
    | '/charts/$slug'
    | '/charts/ticket-price-index'
    | '/insights/$slug'
    | '/reports/$slug'
    | '/brief/'
    | '/charts/'
    | '/insights/'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthorsRoute: typeof AuthorsRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  MethodologyRoute: typeof MethodologyRoute
  NewsletterRoute: typeof NewsletterRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  AuthorSlugRoute: typeof AuthorSlugRoute
  BriefEditionRoute: typeof BriefEditionRoute
  ChartsSlugRoute: typeof ChartsSlugRoute
  ChartsTicketPriceIndexRoute: typeof ChartsTicketPriceIndexRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  ReportsSlugRoute: typeof ReportsSlugRoute
  BriefIndexRoute: typeof BriefIndexRoute
  ChartsIndexRoute: typeof ChartsIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/$slug': {
      id: '/author/$slug'
      path: '/author/$slug'
      fullPath: '/author/$slug'
      preLoaderRoute: typeof AuthorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/': {
      id: '/brief/'
      path: '/brief'
      fullPath: '/brief/'
      preLoaderRoute: typeof BriefIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/$edition': {
      id: '/brief/$edition'
      path: '/brief/$edition'
      fullPath: '/brief/$edition'
      preLoaderRoute: typeof BriefEditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/': {
      id: '/charts/'
      path: '/charts'
      fullPath: '/charts/'
      preLoaderRoute: typeof ChartsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/$slug': {
      id: '/charts/$slug'
      path: '/charts/$slug'
      fullPath: '/charts/$slug'
      preLoaderRoute: typeof ChartsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/ticket-price-index': {
      id: '/charts/ticket-price-index'
      path: '/charts/ticket-price-index'
      fullPath: '/charts/ticket-price-index'
      preLoaderRoute: typeof ChartsTicketPriceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$slug': {
      id: '/reports/$slug'
      path: '/reports/$slug'
      fullPath: '/reports/$slug'
      preLoaderRoute: typeof ReportsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthorsRoute: AuthorsRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  MethodologyRoute: MethodologyRoute,
  NewsletterRoute: NewsletterRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  AuthorSlugRoute: AuthorSlugRoute,
  BriefEditionRoute: BriefEditionRoute,
  ChartsSlugRoute: ChartsSlugRoute,
  ChartsTicketPriceIndexRoute: ChartsTicketPriceIndexRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  ReportsSlugRoute: ReportsSlugRoute,
  BriefIndexRoute: BriefIndexRoute,
  ChartsIndexRoute: ChartsIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
